# set base image (host OS)
FROM registry.aws.abraham.fun/abraham-ai/eden-base

# install python3 & dependencies
RUN apt-get -y update \
    && apt-get install -y software-properties-common \
    && apt-get -y update \
    && add-apt-repository universe
RUN apt-get -y update
RUN apt install -y libgl1-mesa-glx
RUN apt install -y git
RUN apt install -y wget
RUN apt install -y curl
RUN apt-get -y install python3
RUN apt-get -y install python3-pip

